// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsif_OL7_vuGqn2WT4UkUMkBbdLJbcA8k',
    appId: '1:759638883525:web:37e7f1048d551b09fc04ac',
    messagingSenderId: '759638883525',
    projectId: 'projectflutterdoctorcrop',
    authDomain: 'projectflutterdoctorcrop.firebaseapp.com',
    storageBucket: 'projectflutterdoctorcrop.firebasestorage.app',
    measurementId: 'G-WSVR31GB0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGAiENBzVQOfdB1qRfDIYdMeg0DvBOUJM',
    appId: '1:759638883525:android:c75a26d80e33b844fc04ac',
    messagingSenderId: '759638883525',
    projectId: 'projectflutterdoctorcrop',
    storageBucket: 'projectflutterdoctorcrop.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMK45Z2OwouPUowvc7R_4D43c6tD5Wvt4',
    appId: '1:898904213749:ios:b2667447614c50a7ab5dbc',
    messagingSenderId: '898904213749',
    projectId: 'flutterfirebaseeducation-5d8a5',
    storageBucket: 'flutterfirebaseeducation-5d8a5.firebasestorage.app',
    iosBundleId: 'com.example.electricityPaymentAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsif_OL7_vuGqn2WT4UkUMkBbdLJbcA8k',
    appId: '1:759638883525:web:47044751007a9ac8fc04ac',
    messagingSenderId: '759638883525',
    projectId: 'projectflutterdoctorcrop',
    authDomain: 'projectflutterdoctorcrop.firebaseapp.com',
    storageBucket: 'projectflutterdoctorcrop.firebasestorage.app',
    measurementId: 'G-CLJ4V8WLQE',
  );
}
