// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0CeHQnOXXUqKrcL9hGES_Gp2TPlpWHUc',
    appId: '1:898904213749:web:b58c922f8f951a88ab5dbc',
    messagingSenderId: '898904213749',
    projectId: 'flutterfirebaseeducation-5d8a5',
    authDomain: 'flutterfirebaseeducation-5d8a5.firebaseapp.com',
    storageBucket: 'flutterfirebaseeducation-5d8a5.firebasestorage.app',
    measurementId: 'G-29F7BMN4Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1mk77WDVPwF66IAkZ7lnQ_yhq6Jis1Z0',
    appId: '1:898904213749:android:8f5a84ecb8438858ab5dbc',
    messagingSenderId: '898904213749',
    projectId: 'flutterfirebaseeducation-5d8a5',
    storageBucket: 'flutterfirebaseeducation-5d8a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMK45Z2OwouPUowvc7R_4D43c6tD5Wvt4',
    appId: '1:898904213749:ios:b2667447614c50a7ab5dbc',
    messagingSenderId: '898904213749',
    projectId: 'flutterfirebaseeducation-5d8a5',
    storageBucket: 'flutterfirebaseeducation-5d8a5.firebasestorage.app',
    iosBundleId: 'com.example.electricityPaymentAuth',
  );
}
